[package]
name = "starknet_caller"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
starknet = "0.15.1"
tokio = {version = "1.45.0", features = ["full"]}
